jobs:
  eslint:
    container: ghcr.io/elimity-com/insights-client-js:21215375943
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx eslint .

  openapi-ts:
    container: ghcr.io/elimity-com/insights-client-js:21215375943
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx openapi-ts
      - run: git -c safe.directory=/__w/insights-client-js/insights-client-js diff --quiet

  prettier:
    container: ghcr.io/elimity-com/insights-client-js:21215375943
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx prettier -c .

  tsc:
    container: ghcr.io/elimity-com/insights-client-js:21215375943
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx tsc

on: pull_request
